version: '1.0'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://dbuser:dbpassword@db:3030/dbname
      - BROKER_URL=amqp://guest:guest@broker:5672/
    depends_on:
      - db
      - broker

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - db-data:/var/lib/postgresql/data

  broker:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - broker-data:/var/lib/rabbitmq

volumes:
  db-data:
  broker-data:
